### ISSUE TITLE
Edge browser obscures header search control

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#1076]
On MS Edge, the search control in the header is not visible.  A z-index change appears to resolve the issue:

```css
#search {
  z-index: 7000;
}
```
