### ISSUE TITLE
Style cleanup

### ISSUE THREAD

**Issue by jfrankl** [CoastalResilienceNetwork/GeositeFramework#867]
- Close app from navigation (x next to title)

**Comment by jfrankl** [comment]
Code for close app:

###  New HTML

```html
<button class="button-link button-sidebar-plugin-close">
  <i class="icon-cancel"></i>
</button>
```

Context: Sibling of `#left-pane button.nav-apps-button`

### New CSS

```css
.button-sidebar-plugin-close {
  position: absolute;
  right: 5px;
  color: #fff !important;
  opacity: 1;
  background-color: #565656;
  border-radius: 100%;
  bottom: 0;
  height: 22px;
  top: 50%;
  transform: translateY(-50%);
  width: 22px;
}

.button-sidebar-plugin-close .icon-cancel {
  font-size: 10px;
  position: relative;
  left: -2px;
  color: #fff;
}

.sidebar-plugin {
  position: relative;
}

.nav-apps-button {
  padding: 10px 10px 8px;
}
```
